# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed707ce2254f312da0653327492d3fa7a02255e084a42f838f5381104354f35ebd7b3681537f9dacac3ca5d323f35e20f1488545a740c6e587b98e1670099a6e

test:
  secret_key_base: 0fbf8886955ef8932c2e2add70cf0bc0d15ea89d6275cea5ee6f51906c483f243671e4d5a748c6aa1aedb91d477ad4a4c059aa2dffe339842f2092254dec4e34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
